CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS SPLIT_EXP_USER_ENTITY (
	ID UUID PRIMARY KEY,
	ENTITY_TYPE integer NOT NULL
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_USER (
	ID UUID PRIMARY KEY,
	EMAIL text NOT NULL,
	NAME text NOT NULL,
	CONSTRAINT FK_USER_ID FOREIGN KEY(ID) REFERENCES SPLIT_EXP_USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_GROUP (
	ID UUID PRIMARY KEY,
	NAME text NOT NULL,
	CONSTRAINT FK_GROUP_ID FOREIGN KEY(ID) REFERENCES SPLIT_EXP_USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_USER_GROUP_MAPPING (
	ID UUID PRIMARY KEY,
	GROUP_ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	CONSTRAINT FK_UGM_GROUP_ID FOREIGN KEY(GROUP_ID) REFERENCES SPLIT_EXP_GROUP(ID),
	CONSTRAINT FK_UGM_USER_ID FOREIGN KEY(USER_ID) REFERENCES SPLIT_EXP_USER(ID)
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_EVENT (
	ID UUID PRIMARY KEY,
	NAME text NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_EVENT_USER_MAPPING (
	ID UUID PRIMARY KEY,
	EVENT_ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	CONSTRAINT FK_EUM_EVENT_ID FOREIGN KEY(EVENT_ID) REFERENCES SPLIT_EXP_EVENT(ID),
	CONSTRAINT FK_EUM_USER_ID FOREIGN KEY(USER_ID) REFERENCES SPLIT_EXP_USER(ID)
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_EXPENSE (
	ID UUID PRIMARY KEY,
	EVENT_ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	AMOUNT NUMERIC NOT NULL,
	NAME text NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT FK_EXP_USER_ID FOREIGN KEY(USER_ID) REFERENCES SPLIT_EXP_USER(ID)
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_EXPENSE_DISTRIBUTION (
	ID UUID PRIMARY KEY,
	EXPENSE_ID UUID NOT NULL,
	USER_ID UUID NOT NULL,
	USER_CONTRIBUTION NUMERIC NOT NULL,
	CONTRIBUTION_TYPE integer NOT NULL,
	CONSTRAINT FK_ED_EXPENSE_ID FOREIGN KEY(EXPENSE_ID) REFERENCES SPLIT_EXP_EXPENSE(ID),
	CONSTRAINT FK_ED_USER_ID FOREIGN KEY(USER_ID) REFERENCES SPLIT_EXP_USER(ID)
);

CREATE TABLE IF NOT EXISTS SPLIT_EXP_PENDING_TRANSACTIONS (
	ID UUID PRIMARY KEY,
	PAYER_ID UUID NOT NULL,
	RECEIVER_ID UUID NOT NULL,
	AMOUNT NUMERIC NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT FK_PT_PAYER_ID FOREIGN KEY(PAYER_ID) REFERENCES SPLIT_EXP_USER(ID),
	CONSTRAINT FK_PT_RECEIVER_ID FOREIGN KEY(RECEIVER_ID) REFERENCES SPLIT_EXP_USER(ID)
);